<?php
/**
* Function implementing the hooks_menu()
*/
  
function contact_us_menu()
{
    $arrItems = array();
    $arrItems['contact-us'] = array(
        'title'            => '',
        'description'      => 'Site Contact',
        'page callback'    => 'fnSiteContact',
        'access callback'  => TRUE,
    );

    return $arrItems;
}

/**
 * Function for Contact Us 
 */
function fnSiteContact()
{
	global $base_url;

    #Initialise the contacting user details variables.
    
	module_load_include('inc', 'contact_us', 'inc/contactusinfo');
	$objContact = new ContactUsInfo();
    
    $strUserName = "";
    $strUserEmail = "";
    $strUserRegionId = "";
    $strUserMessage = "";
    $strErrorMessage = "";
    
    $arrContactDetailsList = $objContact->getContactInfoDetails();
    
    $arrRegionDetailsList = $objContact->getRegionDetails();
   
    # code for contact form details.
    if (isset($_POST['btnSubmit'])) {
        $strUserName = trim($_POST['name']);
        $strUserEmail = trim($_POST['email']);
        $strUserRegionId = trim($_POST['region']);
        $strUserMessage = trim($_POST['message']);
        $strSubject = "Contact Us Request";
        
        $strErrorMessage = $objContact->fnValidateForm($strUserName, $strUserEmail, $strUserRegionId, $strUserMessage);
        
        if ($strErrorMessage != "") {
            drupal_set_message(t($strErrorMessage), 'error');
        } else {

        	$arrParams = array(
        			'body' => $strUserMessage,
        			'subject' => $strSubject,
        			'headers'=>'simple',
        	);
        	
        	$objRegionNode = node_load($strUserRegionId);
        	$strUserRegionEmail = $objRegionNode->field_region_email['und'][0]['value'];
        	
        	$strToEmail = $strUserRegionEmail;
        	$strFromEmail = $strUserEmail;
        	$arrMailReturnValue = drupal_mail('contact_us', 'send_contact_request', $strToEmail, language_default(), $arrParams, $strFromEmail, TRUE);
        	if($arrMailReturnValue['result']) {
        	   	drupal_set_message(t("Thanks for contacting us"), 'status');
        	}
        	else {
        		drupal_set_message(t("Mail not sent"), 'error');
        	}	   	
        	drupal_goto('contact-us/');
        }
    }

    # Include necessary JS and CSS
    drupal_add_css(drupal_get_path('theme', 'kantar'). '/kantar_custom.css');
   
    # Prepare the array for template.
    $arrListData = array("arrContactDetailsList" => $arrContactDetailsList,
                         "arrRegionDetailsList" => $arrRegionDetailsList,
    					"strUserName" => $strUserName,
                         "strUserEmail" => $strUserEmail,
                         "strUserRegionId" => $strUserRegionId,
                         "strUserMessage" => $strUserMessage,
                         );

    return theme('contact_us', $arrListData);
}



/**
 * Overriding hook_mail to send email
 */
function contact_us_mail($strKey,&$arrMessage,$arrParams) 
{

       switch ($strKey) {
             case 'send_contact_request':
                  $arrMessage['subject']=t($arrParams['subject']);
                  $arrMessage['body'][]=$arrParams['body'];
                  $arrMessage['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
       break;
          }
 }


/**
 * Call Inbuilt hook theme to use templates
 */
function contact_us_theme()
{
    $themes = array(
         'contact_us' => array(
            'template' => 'templates/contact_us',
        ),
    );
    return $themes;
}


?>